name: "duckpandemic"
description: "Duckpandemic is a GitHub Action that updates your README.md with beautiful duck images."
author: "tot0p"
branding:
  icon: "feather"
  color: "yellow"

runs:
  using : "composite"
  steps:
    - name : "Checkout"
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f $GITHUB_ACTION_PATH/src/requirements.txt ]; then pip install -r$GITHUB_ACTION_PATH/src/requirements.txt; fi
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: run python
      shell: bash
      run: |
        python $GITHUB_ACTION_PATH/src/main.py
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
