name : duck pandemic
on:
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v3
        - name: duck
          uses: tot0p/duckpandemic@v1
